version: '3' 

services: 
  nprobe_py:
    image: nprobe_py:latest
    command: [
        "/app/nprobe_py.py",
        "--performance",
        "--ntopng", "tcp://*:1234",
        "--collector-port", "udp://0.0.0.0:2055",
        "-T", "@NTOPNG@"
    ]
    ports:
      - 2055:2055/udp
    build:
      context: ./
      dockerfile: Dockerfile.nprobe_py

  redis: 
    image: "redis:alpine" 
    volumes:
      - ./vol_redis:/data:rw

  ntopng: 
    image: "ntopng:latest"
    command: [
        "ntopng",
        '--community',
        "--redis", "redis",
        "--interface", "tcp://nprobe_py:1234" ,
        '--local-networks', '192.168.1.0/24=LAN,10.1.1.0/24=LAN_SENSORS'
    ]
    ports:
      - "3000:3000" 
    depends_on: 
      - redis
      - nprobe_py
    volumes: 
      - ./vol_ntopng:/var/lib/ntopng:rw
    build:
      context: ./
      dockerfile: Dockerfile.ntopng

