FROM debian:bullseye

ENV LANG C.UTF-8

COPY install_ntop.sh /install_ntop.sh

RUN \
  apt update \
  && apt upgrade -y \
  && apt install -y -q wget lsb-release gnupg \
  && cd /tmp \
  && /install_ntop.sh \
  && apt clean \
  && rm -rf /tmp/* \
  && rm -rf /var/tmp/* \
  && rm -rf /var/lib/apt/lists/*
